/*
 * Built-in triathlon glossary.
 *
 * Each entry:
 *   term     - the acronym / abbreviation / word (required)
 *   full     - what an acronym stands for (optional)
 *   def      - plain-language explanation (required)
 *   category - one of the CATEGORIES below
 *
 * This is the starter list that ships with the app. Anything the user adds
 * themselves is stored separately on their device and merged in at runtime.
 */
window.TRIATHLON_CATEGORIES = [
  'General',
  'Racing',
  'Swim',
  'Bike',
  'Run',
  'Training',
  'Physiology',
  'Gear',
  'Nutrition',
];

window.TRIATHLON_TERMS = [
  // ---- General ----
  { term: 'Tri', full: 'Triathlon', def: 'A multisport race made of a swim, a bike and a run, done back-to-back in that order.', category: 'General' },
  { term: 'Multisport', def: 'Umbrella term for events combining two or more disciplines — triathlon, duathlon, aquathlon, aquabike, etc.', category: 'General' },
  { term: 'Duathlon', def: 'A run–bike–run race. No swim. A common entry point and a winter option.', category: 'General' },
  { term: 'Aquathlon', def: 'A swim followed by a run. No bike.', category: 'General' },
  { term: 'Aquabike', def: 'A swim followed by a bike, with no run. Popular with people managing running injuries.', category: 'General' },
  { term: 'Brick', def: 'A training session that stacks two disciplines back-to-back (usually bike-then-run) to teach the body to switch, especially the heavy "brick legs" feeling off the bike.', category: 'Training' },
  { term: 'Leg', def: 'One of the three parts of the race (the swim leg, the bike leg, the run leg).', category: 'General' },
  { term: 'Discipline', def: 'One of the sports within triathlon: swimming, cycling or running.', category: 'General' },
  { term: 'AG', full: 'Age Grouper', def: 'A non-professional (amateur) athlete who races and is ranked within their age category.', category: 'Racing' },
  { term: 'Age Group', def: 'The bracket you race and are ranked in, usually a 5-year band by sex (e.g. M40–44).', category: 'Racing' },
  { term: 'Pro / Elite', def: 'Athletes racing for prize money and pro rankings, usually starting in their own wave ahead of age groupers.', category: 'Racing' },
  { term: 'FOP / MOP / BOP', full: 'Front / Middle / Back Of Pack', def: 'Informal shorthand for roughly where you finish in the field.', category: 'Racing' },
  { term: 'DNF', full: 'Did Not Finish', def: 'You started the race but did not complete it.', category: 'Racing' },
  { term: 'DNS', full: 'Did Not Start', def: 'You were entered but did not start the race.', category: 'Racing' },
  { term: 'DQ', full: 'Disqualified', def: 'Removed from the results for a rule breach (e.g. drafting, littering, missing equipment).', category: 'Racing' },
  { term: 'PB / PR', full: 'Personal Best / Personal Record', def: 'Your fastest-ever time for a given distance or course.', category: 'General' },
  { term: 'WTC', full: 'World Triathlon Corporation', def: 'The company behind the IRONMAN and 70.3 race brands.', category: 'Racing' },
  { term: 'ITU / World Triathlon', def: 'World Triathlon (formerly the ITU, International Triathlon Union) is the sport’s global governing body, running the World Series and Olympic qualification.', category: 'Racing' },
  { term: 'USAT', full: 'USA Triathlon', def: 'The national governing body for the sport in the United States.', category: 'Racing' },
  { term: 'BTF', full: 'British Triathlon Federation', def: 'The national governing body for triathlon in Great Britain.', category: 'Racing' },

  // ---- Racing / distances ----
  { term: 'IM', full: 'IRONMAN', def: 'The full-distance triathlon: 2.4 mi (3.8 km) swim, 112 mi (180 km) bike, 26.2 mi (42.2 km) marathon run. Also a race brand.', category: 'Racing' },
  { term: '70.3', full: 'IRONMAN 70.3 (Half)', def: 'Half the IRONMAN distance — 70.3 total miles: 1.2 mi swim, 56 mi bike, 13.1 mi run. Also called a "Half".', category: 'Racing' },
  { term: '140.6', def: 'The total mileage of a full IRONMAN (2.4 + 112 + 26.2), used as shorthand for full-distance.', category: 'Racing' },
  { term: 'Olympic / Standard', def: 'Standard-distance triathlon: 1.5 km swim, 40 km bike, 10 km run. The Olympic race format.', category: 'Racing' },
  { term: 'Sprint', def: 'A short-course triathlon, typically ~750 m swim, 20 km bike, 5 km run. A popular first race.', category: 'Racing' },
  { term: 'Super Sprint', def: 'An even shorter format (e.g. 400 m / 10 km / 2.5 km), great for beginners and kids.', category: 'Racing' },
  { term: 'Middle Distance', def: 'Umbrella term for half-IRONMAN-length races (~113 km total).', category: 'Racing' },
  { term: 'Long Course', def: 'Any long triathlon — middle and full distance events.', category: 'Racing' },
  { term: 'Ultra Tri', def: 'Races beyond IRONMAN distance — double, triple or more (e.g. a "Deca").', category: 'Racing' },
  { term: 'Kona', def: 'The IRONMAN World Championship held in Kailua-Kona, Hawaii — the sport’s most famous full-distance race.', category: 'Racing' },
  { term: 'KQ', full: 'Kona Qualifier / Qualified', def: 'Earning (or the act of earning) a slot to the IRONMAN World Championship in Kona.', category: 'Racing' },
  { term: 'Slot / Roll-down', def: 'A championship qualifying place. If a qualifier declines, the slot "rolls down" to the next finisher in that age group.', category: 'Racing' },
  { term: 'M-dot', def: 'The IRONMAN logo (a dot over an M). "An M-dot race" means an official IRONMAN-branded event; "getting the M-dot tattoo" is a finisher tradition.', category: 'Racing' },
  { term: 'WC', full: 'World Championship', def: 'The pinnacle event for a series (e.g. the 70.3 or IRONMAN World Championship).', category: 'Racing' },
  { term: 'Draft-legal', def: 'A race format where riders are allowed to draft (ride in each other’s slipstream). Used in ITU/Olympic racing.', category: 'Racing' },
  { term: 'Non-drafting', def: 'A race where drafting is banned; you must keep a set distance behind the rider ahead. Most age-group IRONMAN/70.3 racing is non-drafting.', category: 'Racing' },
  { term: 'Wave', def: 'A group of athletes started together, usually by age group or sex, a few minutes apart to spread out the field.', category: 'Racing' },
  { term: 'Wave Start', def: 'Starting the race in separate timed groups rather than all at once.', category: 'Racing' },
  { term: 'Rolling Start', def: 'Athletes enter the swim continuously in a self-seeded line rather than in one mass. Your clock starts when you cross the mat.', category: 'Racing' },
  { term: 'Mass Start', def: 'Everyone (or a whole wave) starts at the same instant — often a churning, physical swim.', category: 'Racing' },
  { term: 'Time Trial Start', def: 'Athletes set off one or a few at a time at intervals.', category: 'Racing' },
  { term: 'Cutoff', def: 'A time limit for reaching a checkpoint or finishing. Miss it and you’re pulled from the course.', category: 'Racing' },
  { term: 'Chip Time', def: 'Your time measured from when you personally crossed the start mat to the finish (vs. gun time).', category: 'Racing' },
  { term: 'Gun Time', def: 'Elapsed time from the official start signal, regardless of when you crossed the line.', category: 'Racing' },
  { term: 'Split', def: 'The time for one segment — swim split, bike split, run split, or a per-mile/km split.', category: 'Racing' },
  { term: 'Timing Mat', def: 'A pad on the course that reads your timing chip to record splits.', category: 'Gear' },
  { term: 'Bib', def: 'Your race number, worn on the run (and sometimes the bike). Also identifies you in photos and results.', category: 'Gear' },
  { term: 'Race Belt', def: 'An elastic belt that holds your bib so you can spin it to your back on the bike and front on the run without pinning your kit.', category: 'Gear' },
  { term: 'Body Marking', def: 'Having your race number (and sometimes age) written on your arms and legs before the start.', category: 'Racing' },
  { term: 'Aid Station', def: 'A stop on the bike or run course handing out water, sports drink, gels, food and sometimes ice or sponges.', category: 'Racing' },
  { term: 'Penalty Box / Tent', def: 'Where you serve a time penalty (e.g. for drafting) before continuing.', category: 'Racing' },
  { term: 'Sherpa', def: 'The friend or family member who carries your gear, cheers, and supports you on race day.', category: 'General' },

  // ---- Transition ----
  { term: 'T1', full: 'Transition 1', def: 'The swim-to-bike changeover: strip the wetsuit, helmet on, shoes on, grab the bike.', category: 'Racing' },
  { term: 'T2', full: 'Transition 2', def: 'The bike-to-run changeover: rack the bike, helmet off, running shoes on.', category: 'Racing' },
  { term: 'Transition', def: 'The staging area where you switch disciplines. Fast, tidy transitions save "free" time.', category: 'Racing' },
  { term: 'Brick Legs', def: 'The heavy, wobbly feeling in your legs at the start of the run right after cycling.', category: 'Physiology' },
  { term: 'Flying Mount', def: 'Jumping onto an already-moving bike with shoes pre-clipped to the pedals, to save time leaving T1.', category: 'Bike' },
  { term: 'Flying Dismount', def: 'Stepping off a moving bike with feet on top of the shoes just before the line, to run into T2.', category: 'Bike' },
  { term: 'Rack', def: 'The rail you hang your bike on in transition; also the verb ("rack your bike").', category: 'Racing' },
  { term: 'Mount Line', def: 'The line just outside transition where you’re first allowed to get on and pedal the bike.', category: 'Racing' },
  { term: 'Dismount Line', def: 'The line before transition where you must be off the bike.', category: 'Racing' },

  // ---- Swim ----
  { term: 'OWS', full: 'Open Water Swim', def: 'Swimming in a lake, river or sea rather than a pool — no walls, lines or lane ropes.', category: 'Swim' },
  { term: 'Sighting', def: 'Lifting your eyes forward mid-stroke to check you’re swimming toward the buoy and staying on course.', category: 'Swim' },
  { term: 'Buoy', def: 'A floating marker showing the swim course. You navigate from buoy to buoy.', category: 'Swim' },
  { term: 'Turn Buoy', def: 'A buoy marking a point where the course changes direction — often congested.', category: 'Swim' },
  { term: 'Drafting (swim)', def: 'Swimming just behind or beside another swimmer to ride their slipstream and save energy. Legal in the swim.', category: 'Swim' },
  { term: 'Feet', def: 'Slang for the swimmer ahead of you: "get on their feet" means tuck in behind to draft.', category: 'Swim' },
  { term: 'Washing Machine', def: 'The chaotic, physical scrum of arms and legs at a crowded mass swim start.', category: 'Swim' },
  { term: 'Catch', def: 'The moment early in the stroke when your hand and forearm "grab" the water to pull you forward.', category: 'Swim' },
  { term: 'EVF', full: 'Early Vertical Forearm', def: 'A technique keeping the forearm vertical early in the pull for a stronger catch.', category: 'Swim' },
  { term: 'Bilateral Breathing', def: 'Breathing to both sides (e.g. every 3 strokes), useful for balance and sighting in open water.', category: 'Swim' },
  { term: 'Stroke Rate', def: 'How many strokes you take per minute — a measure of swim cadence.', category: 'Swim' },
  { term: 'SWOLF', def: 'A swim efficiency score: strokes per length plus the seconds it took. Lower is better.', category: 'Swim' },
  { term: 'CSS', full: 'Critical Swim Speed', def: 'An estimate of your sustainable threshold swim pace, used to set training zones.', category: 'Swim' },
  { term: 'Pull Buoy', def: 'A foam float held between the thighs to lift the legs so you focus on the arm pull.', category: 'Gear' },
  { term: 'Paddles', def: 'Plastic plates worn on the hands to build pull strength and feel for the water.', category: 'Gear' },
  { term: 'Tempo Trainer', def: 'A small beeper worn under the cap to keep a set stroke rhythm.', category: 'Gear' },
  { term: 'Wetsuit', def: 'A neoprene suit that keeps you warm and adds buoyancy (and speed) in the swim.', category: 'Gear' },
  { term: 'Wetsuit-legal', def: 'A swim where wetsuits are allowed, decided by water temperature. Above a cutoff, wetsuits are banned.', category: 'Swim' },
  { term: 'Speedsuit / Swimskin', def: 'A thin non-buoyant suit worn over trisuit when the water is too warm for wetsuits.', category: 'Gear' },
  { term: 'Neutral Buoyancy', def: 'Floating balanced in the water with good body position — flat and streamlined.', category: 'Swim' },
  { term: 'Body Position', def: 'How level and streamlined you lie in the water; dropped hips create drag.', category: 'Swim' },
  { term: 'Deadlift Wetsuit / Batman', def: 'The move of peeling the wetsuit down fast in T1; "Batman" arms means the sleeves are inside-out at the wrists.', category: 'Swim' },

  // ---- Bike ----
  { term: 'TT', full: 'Time Trial', def: 'Riding alone against the clock. Triathlon bike legs are essentially a time trial.', category: 'Bike' },
  { term: 'TT Bike', full: 'Time Trial Bike', def: 'An aerodynamic bike with aero bars and steep geometry, built for solo riding against the clock.', category: 'Gear' },
  { term: 'Tri Bike', def: 'A triathlon-specific bike, similar to a TT bike but tuned for comfort over long distances.', category: 'Gear' },
  { term: 'Aero Bars / Aerobars', def: 'Extensions you rest your forearms on to get low and slippery through the air.', category: 'Gear' },
  { term: 'Aero Position', def: 'The low, tucked posture on the aero bars that reduces drag.', category: 'Bike' },
  { term: 'Aero', def: 'Short for aerodynamic — reducing air resistance is the biggest speed lever on the bike.', category: 'Bike' },
  { term: 'CdA', full: 'Coefficient of drag × frontal Area', def: 'A number describing how aerodynamic you and your bike are. Lower CdA = faster for the same effort.', category: 'Bike' },
  { term: 'Watts', def: 'A direct measure of the power you put into the pedals. The core metric of cycling training.', category: 'Bike' },
  { term: 'FTP', full: 'Functional Threshold Power', def: 'The highest power you can hold for about an hour. The anchor for cycling training zones.', category: 'Bike' },
  { term: 'Power Meter', def: 'A device (in the pedals, crank or hub) that measures your power output in watts.', category: 'Gear' },
  { term: 'NP', full: 'Normalized Power', def: 'An adjusted average power that accounts for the surges of a variable ride — a truer sense of effort than raw average.', category: 'Bike' },
  { term: 'IF', full: 'Intensity Factor', def: 'Your normalized power as a fraction of FTP — how hard a ride was relative to threshold.', category: 'Bike' },
  { term: 'VI', full: 'Variability Index', def: 'Normalized power divided by average power. Near 1.0 means a smooth, steady effort — the goal on a tri bike.', category: 'Bike' },
  { term: 'TSS', full: 'Training Stress Score', def: 'A single number for how much a session taxed you, combining duration and intensity.', category: 'Training' },
  { term: 'W/kg', full: 'Watts per Kilogram', def: 'Power divided by body weight — a key climbing and performance ratio.', category: 'Bike' },
  { term: 'Cadence', def: 'Pedal revolutions per minute (RPM). Most triathletes ride around 85–95 rpm.', category: 'Bike' },
  { term: 'Drafting (bike)', def: 'Riding in another rider’s slipstream. Illegal in most age-group tri; you must stay in the "draft zone" rules.', category: 'Bike' },
  { term: 'Draft Zone', def: 'The set distance you must keep behind the bike ahead in non-drafting races (e.g. several bike lengths).', category: 'Bike' },
  { term: 'Blocking', def: 'Illegally riding on the left / not keeping right, obstructing faster riders trying to pass.', category: 'Bike' },
  { term: 'Overtaking Zone', def: 'The time window you’re given to complete a legal pass before you must drop back or move over.', category: 'Bike' },
  { term: 'Pacing', def: 'Managing your effort (power or heart rate) so you don’t blow up and can still run well.', category: 'Bike' },
  { term: 'Negative Split', def: 'Completing the second half of a leg (or race) faster than the first — a sign of good pacing.', category: 'Racing' },
  { term: 'Bonk', def: 'Hitting the wall — running out of carbohydrate fuel, leaving you suddenly weak and empty.', category: 'Physiology' },
  { term: 'Bike Fit', def: 'Professional adjustment of your bike to your body for comfort, power and aerodynamics.', category: 'Gear' },
  { term: 'Groupset', def: 'The bike’s gears, shifters, chain, cranks and brakes as a matched set (e.g. Shimano Di2).', category: 'Gear' },
  { term: 'Di2 / eTap', def: 'Electronic shifting systems (Shimano Di2, SRAM eTap) that shift gears via a button and motor.', category: 'Gear' },
  { term: 'Disc Wheel', def: 'A solid rear wheel that is very aerodynamic on flat, low-wind courses.', category: 'Gear' },
  { term: 'Deep Section', def: 'A wheel with a tall (deep) rim that is more aerodynamic than a shallow box rim.', category: 'Gear' },
  { term: 'BTA', full: 'Between The Arms', def: 'A drink bottle mounted between the aero bars — aerodynamic and easy to sip from.', category: 'Gear' },
  { term: 'Special Needs', def: 'A drop-bag point on long-course bike and run where you collect extra nutrition or spares you packed.', category: 'Racing' },
  { term: 'Mechanical', def: 'A bike problem during the race — a puncture, dropped chain, broken part, etc.', category: 'Bike' },
  { term: 'Clincher / Tubular / Tubeless', def: 'The three main tyre systems: clinchers use an inner tube, tubulars are glued-on, tubeless run sealant with no tube.', category: 'Gear' },

  // ---- Run ----
  { term: 'Run Cadence', def: 'Steps per minute on the run; many aim for a quick, light turnover around 170–180 spm.', category: 'Run' },
  { term: 'Shuffle', def: 'The short, economical stride many triathletes drop into on the run to survive off tired legs.', category: 'Run' },
  { term: 'Run/Walk', def: 'Deliberately alternating running and walking (e.g. through aid stations) to manage fatigue on long races.', category: 'Run' },
  { term: 'The Wall', def: 'The point (often ~30 km of a marathon) where glycogen runs low and everything gets much harder.', category: 'Physiology' },
  { term: 'Death March', def: 'The slow, painful walk/jog to the finish when you’ve run out of energy or overcooked the bike.', category: 'Run' },
  { term: 'Tempo Run', def: 'A sustained "comfortably hard" run at around threshold effort.', category: 'Run' },
  { term: 'Fartlek', def: 'Swedish for "speed play" — unstructured bursts of faster running mixed into an easy run.', category: 'Run' },
  { term: 'Strides', def: 'Short, relaxed accelerations (e.g. 20 s) to sharpen form and turnover.', category: 'Run' },
  { term: 'Off the Bike', def: 'Describes running immediately after cycling — "a quick run off the bike".', category: 'Run' },
  { term: 'GAP', full: 'Grade Adjusted Pace', def: 'Your pace corrected for hills, so an uphill effort is compared fairly to flat running.', category: 'Run' },

  // ---- Training ----
  { term: 'Base', def: 'A block of mostly easy, high-volume aerobic training that builds endurance foundations.', category: 'Training' },
  { term: 'Build', def: 'A phase adding intensity and race-specific work on top of your base.', category: 'Training' },
  { term: 'Peak', def: 'The highest-load part of training just before you taper.', category: 'Training' },
  { term: 'Taper', def: 'Reducing training volume in the days/weeks before a race so you arrive fresh and sharp.', category: 'Training' },
  { term: 'Periodization', def: 'Structuring training into phases (base, build, peak, taper) to peak at the right time.', category: 'Training' },
  { term: 'Volume', def: 'How much you train — total hours or distance.', category: 'Training' },
  { term: 'Intensity', def: 'How hard you train — the effort level of sessions.', category: 'Training' },
  { term: 'Zone 2 / Z2', def: 'Easy aerobic training — conversational effort. The bread-and-butter of endurance base building.', category: 'Training' },
  { term: 'LSD', full: 'Long Slow Distance', def: 'Long, easy sessions that build aerobic endurance.', category: 'Training' },
  { term: 'Intervals', def: 'Repeated hard efforts with rest between, to raise fitness at higher intensities.', category: 'Training' },
  { term: 'Threshold', def: 'The effort you can just sustain before fatigue rises sharply — a key training zone (e.g. FTP, CSS).', category: 'Training' },
  { term: 'VO2max', def: 'The maximum rate your body can use oxygen — a ceiling for aerobic performance. Also a hard training zone.', category: 'Physiology' },
  { term: 'RPE', full: 'Rate of Perceived Exertion', def: 'A subjective 1–10 scale of how hard an effort feels — a simple way to gauge intensity.', category: 'Training' },
  { term: 'HR / HRM', full: 'Heart Rate / Heart Rate Monitor', def: 'Your beats per minute, and the strap or watch that measures it, used to guide effort.', category: 'Gear' },
  { term: 'LTHR', full: 'Lactate Threshold Heart Rate', def: 'The heart rate at your lactate threshold, used to set heart-rate training zones.', category: 'Physiology' },
  { term: 'Max HR', full: 'Maximum Heart Rate', def: 'The highest heart rate you can reach, used as a reference for zones.', category: 'Physiology' },
  { term: 'CTL / ATL / TSB', full: 'Chronic / Acute Training Load, Training Stress Balance', def: 'Fitness (CTL), fatigue (ATL) and "form" (TSB = fitness minus fatigue) tracked over time to time your peak.', category: 'Training' },
  { term: 'Form', def: 'How fresh and race-ready you are (TSB). Positive form usually means rested; deep negative means fatigued.', category: 'Training' },
  { term: 'Overtraining / OTS', full: 'Overtraining Syndrome', def: 'Deep, lasting fatigue and performance loss from too much load and too little recovery.', category: 'Physiology' },
  { term: 'Recovery', def: 'Rest, easy sessions, sleep and nutrition that let the body adapt and get stronger.', category: 'Training' },
  { term: 'Active Recovery', def: 'Very easy movement (a spin or gentle swim) to aid recovery without adding real stress.', category: 'Training' },
  { term: 'Deload / Recovery Week', def: 'A planned lighter week to absorb training and avoid burnout.', category: 'Training' },
  { term: 'Time Crunched', def: 'Training on limited hours by favouring shorter, more intense sessions.', category: 'Training' },
  { term: 'Two-a-day / Double', def: 'Two training sessions in one day, common when volume is high.', category: 'Training' },
  { term: 'Open Water', def: 'Practising in lakes/sea to get comfortable with sighting, wetsuits and no walls before race day.', category: 'Training' },
  { term: 'Trainer / Turbo', def: 'An indoor bike trainer. A "smart trainer" adjusts resistance and connects to apps like Zwift.', category: 'Gear' },
  { term: 'Zwift', def: 'A popular virtual training app for riding and running indoors in a game-like world.', category: 'Gear' },
  { term: 'Treadmill / Dreadmill', def: 'Indoor running belt; "dreadmill" is the affectionate groan for it.', category: 'Gear' },

  // ---- Physiology / body ----
  { term: 'Aerobic', def: 'Energy produced with oxygen — the sustainable engine behind endurance racing.', category: 'Physiology' },
  { term: 'Anaerobic', def: 'Energy produced without enough oxygen, for short hard efforts. Fatigues quickly.', category: 'Physiology' },
  { term: 'Lactate / Lactic', def: 'A by-product of hard effort. Rising blood lactate marks the threshold between easy and unsustainable pace.', category: 'Physiology' },
  { term: 'Glycogen', def: 'Stored carbohydrate in muscles and liver — your main fuel for hard endurance efforts.', category: 'Physiology' },
  { term: 'Cramp', def: 'A sudden, painful muscle spasm, often late in a race from fatigue, fluid or electrolyte issues.', category: 'Physiology' },
  { term: 'Hyponatremia', def: 'Dangerously low blood sodium from drinking too much plain water without electrolytes.', category: 'Physiology' },
  { term: 'DOMS', full: 'Delayed Onset Muscle Soreness', def: 'The muscle soreness that peaks a day or two after a hard or new session.', category: 'Physiology' },
  { term: 'Economy', def: 'How little energy you use to hold a given pace — better economy means faster for the same effort.', category: 'Physiology' },
  { term: 'Threshold Pace', def: 'The pace you can hold at lactate threshold — a benchmark for run and swim training.', category: 'Physiology' },

  // ---- Nutrition ----
  { term: 'Gel', def: 'A concentrated carbohydrate sachet for quick fuel during racing and long sessions.', category: 'Nutrition' },
  { term: 'Carbs/hr', def: 'Grams of carbohydrate eaten per hour of racing — a key fuelling target (often 60–90 g/hr, sometimes more).', category: 'Nutrition' },
  { term: 'Electrolytes', def: 'Salts (sodium, potassium, magnesium) lost in sweat and replaced to keep muscles and fluid balance working.', category: 'Nutrition' },
  { term: 'Bottle / Bidon', def: 'Your drinks bottle. "Bidon" is the French term used in cycling.', category: 'Gear' },
  { term: 'Hydration', def: 'Managing fluid intake before, during and after training and racing.', category: 'Nutrition' },
  { term: 'Fuelling', def: 'Your plan for taking in carbohydrate and fluid to keep energy up through a long race.', category: 'Nutrition' },
  { term: 'Gut Training', def: 'Practising race-day fuelling in training so your stomach can handle the carbs and fluids on the day.', category: 'Nutrition' },
  { term: 'Carb Loading', def: 'Eating extra carbohydrate in the days before a long race to top up glycogen stores.', category: 'Nutrition' },
  { term: 'Real Food', def: 'Whole foods (bananas, rice cakes, chews) used alongside or instead of gels for fuelling.', category: 'Nutrition' },

  // ---- Gear / kit ----
  { term: 'Trisuit', def: 'A one- or two-piece suit worn for the whole race — swim, bike and run — with a light quick-drying pad.', category: 'Gear' },
  { term: 'Tri Shorts', def: 'Padded shorts with a thin chamois designed to be swum in, ridden in and run in.', category: 'Gear' },
  { term: 'Chamois', def: 'The padded insert in cycling/tri shorts. "Chamois cream" reduces chafing and saddle sores.', category: 'Gear' },
  { term: 'Cleats', def: 'The plates on the bottom of cycling shoes that clip into the pedals.', category: 'Gear' },
  { term: 'Clipless Pedals', def: 'Pedals your shoe cleat clips into (confusingly named — there’s no toe-clip cage).', category: 'Gear' },
  { term: 'Speed Laces / Elastic Laces', def: 'Stretchy or toggle laces that let you slip running shoes on instantly in T2.', category: 'Gear' },
  { term: 'Garmin / Wahoo', def: 'Popular brands of GPS watches and bike computers used to record and guide training and racing.', category: 'Gear' },
  { term: 'GPS Watch', def: 'A wrist device that tracks pace, distance, heart rate and more across all three disciplines.', category: 'Gear' },
  { term: 'Bike Computer', def: 'A handlebar-mounted unit showing speed, power, heart rate and navigation while riding.', category: 'Gear' },
  { term: 'DI / Dropper', def: 'Small aero add-ons like hydration or storage systems that tidy the bike; also "DI" for Di2 electronic shifting.', category: 'Gear' },
  { term: 'Anti-fog', def: 'Treatment or spit used to keep swim goggles clear.', category: 'Gear' },
  { term: 'Goggles', def: 'Eye protection for swimming; tinted for bright open water, clear for low light.', category: 'Gear' },
  { term: 'Swim Cap', def: 'A latex or silicone cap, often colour-coded to your wave and required by most races for visibility.', category: 'Gear' },
];
