/*
 * Built-in triathlon glossary.
 *
 * Each entry:
 *   term     - the acronym / abbreviation / word (required)
 *   full     - what an acronym stands for (optional)
 *   def      - plain-language explanation (required)
 *   category - one of the CATEGORIES below
 *
 * This is the starter list that ships with the app. Anything the user adds
 * themselves is stored separately on their device and merged in at runtime.
 */
window.TRIATHLON_CATEGORIES = [
  'General',
  'Racing',
  'Swim',
  'Bike',
  'Run',
  'Training',
  'Physiology',
  'Gear',
  'Nutrition',
  'Strength',
  'Workout',
  'Ultra',
  'Longevity',
];

window.TRIATHLON_TERMS = [
  // ---- General ----
  { term: 'Tri', full: 'Triathlon', def: 'A multisport race made of a swim, a bike and a run, done back-to-back in that order.', category: 'General' },
  { term: 'Multisport', def: 'Umbrella term for events combining two or more disciplines — triathlon, duathlon, aquathlon, aquabike, etc.', category: 'General' },
  { term: 'Duathlon', def: 'A run–bike–run race. No swim. A common entry point and a winter option.', category: 'General' },
  { term: 'Aquathlon', def: 'A swim followed by a run. No bike.', category: 'General' },
  { term: 'Aquabike', def: 'A swim followed by a bike, with no run. Popular with people managing running injuries.', category: 'General' },
  { term: 'Brick', def: 'A training session that stacks two disciplines back-to-back (usually bike-then-run) to teach the body to switch, especially the heavy "brick legs" feeling off the bike.', category: 'Training' },
  { term: 'Leg', def: 'One of the three parts of the race (the swim leg, the bike leg, the run leg).', category: 'General' },
  { term: 'Discipline', def: 'One of the sports within triathlon: swimming, cycling or running.', category: 'General' },
  { term: 'AG', full: 'Age Grouper', def: 'A non-professional (amateur) athlete who races and is ranked within their age category.', category: 'Racing' },
  { term: 'Age Group', def: 'The bracket you race and are ranked in, usually a 5-year band by sex (e.g. M40–44).', category: 'Racing' },
  { term: 'Pro / Elite', def: 'Athletes racing for prize money and pro rankings, usually starting in their own wave ahead of age groupers.', category: 'Racing' },
  { term: 'FOP / MOP / BOP', full: 'Front / Middle / Back Of Pack', def: 'Informal shorthand for roughly where you finish in the field.', category: 'Racing' },
  { term: 'DNF', full: 'Did Not Finish', def: 'You started the race but did not complete it.', category: 'Racing' },
  { term: 'DNS', full: 'Did Not Start', def: 'You were entered but did not start the race.', category: 'Racing' },
  { term: 'DQ', full: 'Disqualified', def: 'Removed from the results for a rule breach (e.g. drafting, littering, missing equipment).', category: 'Racing' },
  { term: 'PB / PR', full: 'Personal Best / Personal Record', def: 'Your fastest-ever time for a given distance or course.', category: 'General' },
  { term: 'WTC', full: 'World Triathlon Corporation', def: 'The company behind the IRONMAN and 70.3 race brands.', category: 'Racing' },
  { term: 'ITU / World Triathlon', def: 'World Triathlon (formerly the ITU, International Triathlon Union) is the sport’s global governing body, running the World Series and Olympic qualification.', category: 'Racing' },
  { term: 'USAT', full: 'USA Triathlon', def: 'The national governing body for the sport in the United States.', category: 'Racing' },
  { term: 'BTF', full: 'British Triathlon Federation', def: 'The national governing body for triathlon in Great Britain.', category: 'Racing' },

  // ---- Racing / distances ----
  { term: 'IM', full: 'IRONMAN', def: 'The full-distance triathlon: 2.4 mi (3.8 km) swim, 112 mi (180 km) bike, 26.2 mi (42.2 km) marathon run. Also a race brand.', category: 'Racing' },
  { term: '70.3', full: 'IRONMAN 70.3 (Half)', def: 'Half the IRONMAN distance — 70.3 total miles: 1.2 mi swim, 56 mi bike, 13.1 mi run. Also called a "Half".', category: 'Racing' },
  { term: '140.6', def: 'The total mileage of a full IRONMAN (2.4 + 112 + 26.2), used as shorthand for full-distance.', category: 'Racing' },
  { term: 'Olympic / Standard', def: 'Standard-distance triathlon: 1.5 km swim, 40 km bike, 10 km run. The Olympic race format.', category: 'Racing' },
  { term: 'Sprint', def: 'A short-course triathlon, typically ~750 m swim, 20 km bike, 5 km run. A popular first race.', category: 'Racing' },
  { term: 'Super Sprint', def: 'An even shorter format (e.g. 400 m / 10 km / 2.5 km), great for beginners and kids.', category: 'Racing' },
  { term: 'Middle Distance', def: 'Umbrella term for half-IRONMAN-length races (~113 km total).', category: 'Racing' },
  { term: 'Long Course', def: 'Any long triathlon — middle and full distance events.', category: 'Racing' },
  { term: 'Ultra Tri', def: 'Races beyond IRONMAN distance — double, triple or more (e.g. a "Deca").', category: 'Racing' },
  { term: 'Kona', def: 'The IRONMAN World Championship held in Kailua-Kona, Hawaii — the sport’s most famous full-distance race.', category: 'Racing' },
  { term: 'KQ', full: 'Kona Qualifier / Qualified', def: 'Earning (or the act of earning) a slot to the IRONMAN World Championship in Kona.', category: 'Racing' },
  { term: 'Slot / Roll-down', def: 'A championship qualifying place. If a qualifier declines, the slot "rolls down" to the next finisher in that age group.', category: 'Racing' },
  { term: 'M-dot', def: 'The IRONMAN logo (a dot over an M). "An M-dot race" means an official IRONMAN-branded event; "getting the M-dot tattoo" is a finisher tradition.', category: 'Racing' },
  { term: 'WC', full: 'World Championship', def: 'The pinnacle event for a series (e.g. the 70.3 or IRONMAN World Championship).', category: 'Racing' },
  { term: 'Draft-legal', def: 'A race format where riders are allowed to draft (ride in each other’s slipstream). Used in ITU/Olympic racing.', category: 'Racing' },
  { term: 'Non-drafting', def: 'A race where drafting is banned; you must keep a set distance behind the rider ahead. Most age-group IRONMAN/70.3 racing is non-drafting.', category: 'Racing' },
  { term: 'Wave', def: 'A group of athletes started together, usually by age group or sex, a few minutes apart to spread out the field.', category: 'Racing' },
  { term: 'Wave Start', def: 'Starting the race in separate timed groups rather than all at once.', category: 'Racing' },
  { term: 'Rolling Start', def: 'Athletes enter the swim continuously in a self-seeded line rather than in one mass. Your clock starts when you cross the mat.', category: 'Racing' },
  { term: 'Mass Start', def: 'Everyone (or a whole wave) starts at the same instant — often a churning, physical swim.', category: 'Racing' },
  { term: 'Time Trial Start', def: 'Athletes set off one or a few at a time at intervals.', category: 'Racing' },
  { term: 'Cutoff', def: 'A time limit for reaching a checkpoint or finishing. Miss it and you’re pulled from the course.', category: 'Racing' },
  { term: 'Chip Time', def: 'Your time measured from when you personally crossed the start mat to the finish (vs. gun time).', category: 'Racing' },
  { term: 'Gun Time', def: 'Elapsed time from the official start signal, regardless of when you crossed the line.', category: 'Racing' },
  { term: 'Split', def: 'The time for one segment — swim split, bike split, run split, or a per-mile/km split.', category: 'Racing' },
  { term: 'Timing Mat', def: 'A pad on the course that reads your timing chip to record splits.', category: 'Gear' },
  { term: 'Bib', def: 'Your race number, worn on the run (and sometimes the bike). Also identifies you in photos and results.', category: 'Gear' },
  { term: 'Race Belt', def: 'An elastic belt that holds your bib so you can spin it to your back on the bike and front on the run without pinning your kit.', category: 'Gear' },
  { term: 'Body Marking', def: 'Having your race number (and sometimes age) written on your arms and legs before the start.', category: 'Racing' },
  { term: 'Aid Station', def: 'A stop on the bike or run course handing out water, sports drink, gels, food and sometimes ice or sponges.', category: 'Racing' },
  { term: 'Penalty Box / Tent', def: 'Where you serve a time penalty (e.g. for drafting) before continuing.', category: 'Racing' },
  { term: 'Sherpa', def: 'The friend or family member who carries your gear, cheers, and supports you on race day.', category: 'General' },

  // ---- Transition ----
  { term: 'T1', full: 'Transition 1', def: 'The swim-to-bike changeover: strip the wetsuit, helmet on, shoes on, grab the bike.', category: 'Racing' },
  { term: 'T2', full: 'Transition 2', def: 'The bike-to-run changeover: rack the bike, helmet off, running shoes on.', category: 'Racing' },
  { term: 'Transition', def: 'The staging area where you switch disciplines. Fast, tidy transitions save "free" time.', category: 'Racing' },
  { term: 'Brick Legs', def: 'The heavy, wobbly feeling in your legs at the start of the run right after cycling.', category: 'Physiology' },
  { term: 'Flying Mount', def: 'Jumping onto an already-moving bike with shoes pre-clipped to the pedals, to save time leaving T1.', category: 'Bike' },
  { term: 'Flying Dismount', def: 'Stepping off a moving bike with feet on top of the shoes just before the line, to run into T2.', category: 'Bike' },
  { term: 'Rack', def: 'The rail you hang your bike on in transition; also the verb ("rack your bike").', category: 'Racing' },
  { term: 'Mount Line', def: 'The line just outside transition where you’re first allowed to get on and pedal the bike.', category: 'Racing' },
  { term: 'Dismount Line', def: 'The line before transition where you must be off the bike.', category: 'Racing' },

  // ---- Swim ----
  { term: 'OWS', full: 'Open Water Swim', def: 'Swimming in a lake, river or sea rather than a pool — no walls, lines or lane ropes.', category: 'Swim' },
  { term: 'Sighting', def: 'Lifting your eyes forward mid-stroke to check you’re swimming toward the buoy and staying on course.', category: 'Swim' },
  { term: 'Buoy', def: 'A floating marker showing the swim course. You navigate from buoy to buoy.', category: 'Swim' },
  { term: 'Turn Buoy', def: 'A buoy marking a point where the course changes direction — often congested.', category: 'Swim' },
  { term: 'Drafting (swim)', def: 'Swimming just behind or beside another swimmer to ride their slipstream and save energy. Legal in the swim.', category: 'Swim' },
  { term: 'Feet', def: 'Slang for the swimmer ahead of you: "get on their feet" means tuck in behind to draft.', category: 'Swim' },
  { term: 'Washing Machine', def: 'The chaotic, physical scrum of arms and legs at a crowded mass swim start.', category: 'Swim' },
  { term: 'Catch', def: 'The moment early in the stroke when your hand and forearm "grab" the water to pull you forward.', category: 'Swim' },
  { term: 'EVF', full: 'Early Vertical Forearm', def: 'A technique keeping the forearm vertical early in the pull for a stronger catch.', category: 'Swim' },
  { term: 'Bilateral Breathing', def: 'Breathing to both sides (e.g. every 3 strokes), useful for balance and sighting in open water.', category: 'Swim' },
  { term: 'Stroke Rate', def: 'How many strokes you take per minute — a measure of swim cadence.', category: 'Swim' },
  { term: 'SWOLF', def: 'A swim efficiency score: strokes per length plus the seconds it took. Lower is better.', category: 'Swim' },
  { term: 'CSS', full: 'Critical Swim Speed', def: 'An estimate of your sustainable threshold swim pace, used to set training zones.', category: 'Swim' },
  { term: 'Pull Buoy', def: 'A foam float held between the thighs to lift the legs so you focus on the arm pull.', category: 'Gear' },
  { term: 'Paddles', def: 'Plastic plates worn on the hands to build pull strength and feel for the water.', category: 'Gear' },
  { term: 'Tempo Trainer', def: 'A small beeper worn under the cap to keep a set stroke rhythm.', category: 'Gear' },
  { term: 'Wetsuit', def: 'A neoprene suit that keeps you warm and adds buoyancy (and speed) in the swim.', category: 'Gear' },
  { term: 'Wetsuit-legal', def: 'A swim where wetsuits are allowed, decided by water temperature. Above a cutoff, wetsuits are banned.', category: 'Swim' },
  { term: 'Speedsuit / Swimskin', def: 'A thin non-buoyant suit worn over trisuit when the water is too warm for wetsuits.', category: 'Gear' },
  { term: 'Neutral Buoyancy', def: 'Floating balanced in the water with good body position — flat and streamlined.', category: 'Swim' },
  { term: 'Body Position', def: 'How level and streamlined you lie in the water; dropped hips create drag.', category: 'Swim' },
  { term: 'Deadlift Wetsuit / Batman', def: 'The move of peeling the wetsuit down fast in T1; "Batman" arms means the sleeves are inside-out at the wrists.', category: 'Swim' },

  // ---- Bike ----
  { term: 'TT', full: 'Time Trial', def: 'Riding alone against the clock. Triathlon bike legs are essentially a time trial.', category: 'Bike' },
  { term: 'TT Bike', full: 'Time Trial Bike', def: 'An aerodynamic bike with aero bars and steep geometry, built for solo riding against the clock.', category: 'Gear' },
  { term: 'Tri Bike', def: 'A triathlon-specific bike, similar to a TT bike but tuned for comfort over long distances.', category: 'Gear' },
  { term: 'Aero Bars / Aerobars', def: 'Extensions you rest your forearms on to get low and slippery through the air.', category: 'Gear' },
  { term: 'Aero Position', def: 'The low, tucked posture on the aero bars that reduces drag.', category: 'Bike' },
  { term: 'Aero', def: 'Short for aerodynamic — reducing air resistance is the biggest speed lever on the bike.', category: 'Bike' },
  { term: 'CdA', full: 'Coefficient of drag × frontal Area', def: 'A number describing how aerodynamic you and your bike are. Lower CdA = faster for the same effort.', category: 'Bike' },
  { term: 'Watts', def: 'A direct measure of the power you put into the pedals. The core metric of cycling training.', category: 'Bike' },
  { term: 'FTP', full: 'Functional Threshold Power', def: 'The highest power you can hold for about an hour. The anchor for cycling training zones.', category: 'Bike' },
  { term: 'Power Meter', def: 'A device (in the pedals, crank or hub) that measures your power output in watts.', category: 'Gear' },
  { term: 'NP', full: 'Normalized Power', def: 'An adjusted average power that accounts for the surges of a variable ride — a truer sense of effort than raw average.', category: 'Bike' },
  { term: 'IF', full: 'Intensity Factor', def: 'Your normalized power as a fraction of FTP — how hard a ride was relative to threshold.', category: 'Bike' },
  { term: 'VI', full: 'Variability Index', def: 'Normalized power divided by average power. Near 1.0 means a smooth, steady effort — the goal on a tri bike.', category: 'Bike' },
  { term: 'TSS', full: 'Training Stress Score', def: 'A single number for how much a session taxed you, combining duration and intensity.', category: 'Training' },
  { term: 'W/kg', full: 'Watts per Kilogram', def: 'Power divided by body weight — a key climbing and performance ratio.', category: 'Bike' },
  { term: 'Cadence', def: 'Pedal revolutions per minute (RPM). Most triathletes ride around 85–95 rpm.', category: 'Bike' },
  { term: 'Drafting (bike)', def: 'Riding in another rider’s slipstream. Illegal in most age-group tri; you must stay in the "draft zone" rules.', category: 'Bike' },
  { term: 'Draft Zone', def: 'The set distance you must keep behind the bike ahead in non-drafting races (e.g. several bike lengths).', category: 'Bike' },
  { term: 'Blocking', def: 'Illegally riding on the left / not keeping right, obstructing faster riders trying to pass.', category: 'Bike' },
  { term: 'Overtaking Zone', def: 'The time window you’re given to complete a legal pass before you must drop back or move over.', category: 'Bike' },
  { term: 'Pacing', def: 'Managing your effort (power or heart rate) so you don’t blow up and can still run well.', category: 'Bike' },
  { term: 'Negative Split', def: 'Completing the second half of a leg (or race) faster than the first — a sign of good pacing.', category: 'Racing' },
  { term: 'Bonk', def: 'Hitting the wall — running out of carbohydrate fuel, leaving you suddenly weak and empty.', category: 'Physiology' },
  { term: 'Bike Fit', def: 'Professional adjustment of your bike to your body for comfort, power and aerodynamics.', category: 'Gear' },
  { term: 'Groupset', def: 'The bike’s gears, shifters, chain, cranks and brakes as a matched set (e.g. Shimano Di2).', category: 'Gear' },
  { term: 'Di2 / eTap', def: 'Electronic shifting systems (Shimano Di2, SRAM eTap) that shift gears via a button and motor.', category: 'Gear' },
  { term: 'Disc Wheel', def: 'A solid rear wheel that is very aerodynamic on flat, low-wind courses.', category: 'Gear' },
  { term: 'Deep Section', def: 'A wheel with a tall (deep) rim that is more aerodynamic than a shallow box rim.', category: 'Gear' },
  { term: 'BTA', full: 'Between The Arms', def: 'A drink bottle mounted between the aero bars — aerodynamic and easy to sip from.', category: 'Gear' },
  { term: 'Special Needs', def: 'A drop-bag point on long-course bike and run where you collect extra nutrition or spares you packed.', category: 'Racing' },
  { term: 'Mechanical', def: 'A bike problem during the race — a puncture, dropped chain, broken part, etc.', category: 'Bike' },
  { term: 'Clincher / Tubular / Tubeless', def: 'The three main tyre systems: clinchers use an inner tube, tubulars are glued-on, tubeless run sealant with no tube.', category: 'Gear' },

  // ---- Run ----
  { term: 'Run Cadence', def: 'Steps per minute on the run; many aim for a quick, light turnover around 170–180 spm.', category: 'Run' },
  { term: 'Shuffle', def: 'The short, economical stride many triathletes drop into on the run to survive off tired legs.', category: 'Run' },
  { term: 'Run/Walk', def: 'Deliberately alternating running and walking (e.g. through aid stations) to manage fatigue on long races.', category: 'Run' },
  { term: 'The Wall', def: 'The point (often ~30 km of a marathon) where glycogen runs low and everything gets much harder.', category: 'Physiology' },
  { term: 'Death March', def: 'The slow, painful walk/jog to the finish when you’ve run out of energy or overcooked the bike.', category: 'Run' },
  { term: 'Tempo Run', def: 'A sustained "comfortably hard" run at around threshold effort.', category: 'Run' },
  { term: 'Fartlek', def: 'Swedish for "speed play" — unstructured bursts of faster running mixed into an easy run.', category: 'Run' },
  { term: 'Strides', def: 'Short, relaxed accelerations (e.g. 20 s) to sharpen form and turnover.', category: 'Run' },
  { term: 'Off the Bike', def: 'Describes running immediately after cycling — "a quick run off the bike".', category: 'Run' },
  { term: 'GAP', full: 'Grade Adjusted Pace', def: 'Your pace corrected for hills, so an uphill effort is compared fairly to flat running.', category: 'Run' },

  // ---- Training ----
  { term: 'Base', def: 'A block of mostly easy, high-volume aerobic training that builds endurance foundations.', category: 'Training' },
  { term: 'Build', def: 'A phase adding intensity and race-specific work on top of your base.', category: 'Training' },
  { term: 'Peak', def: 'The highest-load part of training just before you taper.', category: 'Training' },
  { term: 'Taper', def: 'Reducing training volume in the days/weeks before a race so you arrive fresh and sharp.', category: 'Training' },
  { term: 'Periodization', def: 'Structuring training into phases (base, build, peak, taper) to peak at the right time.', category: 'Training' },
  { term: 'Volume', def: 'How much you train — total hours or distance.', category: 'Training' },
  { term: 'Intensity', def: 'How hard you train — the effort level of sessions.', category: 'Training' },
  { term: 'Zone 2 / Z2', def: 'Easy aerobic training — conversational effort. The bread-and-butter of endurance base building.', category: 'Training' },
  { term: 'LSD', full: 'Long Slow Distance', def: 'Long, easy sessions that build aerobic endurance.', category: 'Training' },
  { term: 'Intervals', def: 'Repeated hard efforts with rest between, to raise fitness at higher intensities.', category: 'Training' },
  { term: 'Threshold', def: 'The effort you can just sustain before fatigue rises sharply — a key training zone (e.g. FTP, CSS).', category: 'Training' },
  { term: 'VO2max', def: 'The maximum rate your body can use oxygen — a ceiling for aerobic performance. Also a hard training zone.', category: 'Physiology' },
  { term: 'RPE', full: 'Rate of Perceived Exertion', def: 'A subjective 1–10 scale of how hard an effort feels — a simple way to gauge intensity.', category: 'Training' },
  { term: 'HR / HRM', full: 'Heart Rate / Heart Rate Monitor', def: 'Your beats per minute, and the strap or watch that measures it, used to guide effort.', category: 'Gear' },
  { term: 'LTHR', full: 'Lactate Threshold Heart Rate', def: 'The heart rate at your lactate threshold, used to set heart-rate training zones.', category: 'Physiology' },
  { term: 'Max HR', full: 'Maximum Heart Rate', def: 'The highest heart rate you can reach, used as a reference for zones.', category: 'Physiology' },
  { term: 'CTL / ATL / TSB', full: 'Chronic / Acute Training Load, Training Stress Balance', def: 'Fitness (CTL), fatigue (ATL) and "form" (TSB = fitness minus fatigue) tracked over time to time your peak.', category: 'Training' },
  { term: 'Form', def: 'How fresh and race-ready you are (TSB). Positive form usually means rested; deep negative means fatigued.', category: 'Training' },
  { term: 'Overtraining / OTS', full: 'Overtraining Syndrome', def: 'Deep, lasting fatigue and performance loss from too much load and too little recovery.', category: 'Physiology' },
  { term: 'Recovery', def: 'Rest, easy sessions, sleep and nutrition that let the body adapt and get stronger.', category: 'Training' },
  { term: 'Active Recovery', def: 'Very easy movement (a spin or gentle swim) to aid recovery without adding real stress.', category: 'Training' },
  { term: 'Deload / Recovery Week', def: 'A planned lighter week to absorb training and avoid burnout.', category: 'Training' },
  { term: 'Time Crunched', def: 'Training on limited hours by favouring shorter, more intense sessions.', category: 'Training' },
  { term: 'Two-a-day / Double', def: 'Two training sessions in one day, common when volume is high.', category: 'Training' },
  { term: 'Open Water', def: 'Practising in lakes/sea to get comfortable with sighting, wetsuits and no walls before race day.', category: 'Training' },
  { term: 'Trainer / Turbo', def: 'An indoor bike trainer. A "smart trainer" adjusts resistance and connects to apps like Zwift.', category: 'Gear' },
  { term: 'Zwift', def: 'A popular virtual training app for riding and running indoors in a game-like world.', category: 'Gear' },
  { term: 'Treadmill / Dreadmill', def: 'Indoor running belt; "dreadmill" is the affectionate groan for it.', category: 'Gear' },

  // ---- Physiology / body ----
  { term: 'Aerobic', def: 'Energy produced with oxygen — the sustainable engine behind endurance racing.', category: 'Physiology' },
  { term: 'Anaerobic', def: 'Energy produced without enough oxygen, for short hard efforts. Fatigues quickly.', category: 'Physiology' },
  { term: 'Lactate / Lactic', def: 'A by-product of hard effort. Rising blood lactate marks the threshold between easy and unsustainable pace.', category: 'Physiology' },
  { term: 'Glycogen', def: 'Stored carbohydrate in muscles and liver — your main fuel for hard endurance efforts.', category: 'Physiology' },
  { term: 'Cramp', def: 'A sudden, painful muscle spasm, often late in a race from fatigue, fluid or electrolyte issues.', category: 'Physiology' },
  { term: 'Hyponatremia', def: 'Dangerously low blood sodium from drinking too much plain water without electrolytes.', category: 'Physiology' },
  { term: 'DOMS', full: 'Delayed Onset Muscle Soreness', def: 'The muscle soreness that peaks a day or two after a hard or new session.', category: 'Physiology' },
  { term: 'Economy', def: 'How little energy you use to hold a given pace — better economy means faster for the same effort.', category: 'Physiology' },
  { term: 'Threshold Pace', def: 'The pace you can hold at lactate threshold — a benchmark for run and swim training.', category: 'Physiology' },

  // ---- Nutrition ----
  { term: 'Gel', def: 'A concentrated carbohydrate sachet for quick fuel during racing and long sessions.', category: 'Nutrition' },
  { term: 'Carbs/hr', def: 'Grams of carbohydrate eaten per hour of racing — a key fuelling target (often 60–90 g/hr, sometimes more).', category: 'Nutrition' },
  { term: 'Electrolytes', def: 'Salts (sodium, potassium, magnesium) lost in sweat and replaced to keep muscles and fluid balance working.', category: 'Nutrition' },
  { term: 'Bottle / Bidon', def: 'Your drinks bottle. "Bidon" is the French term used in cycling.', category: 'Gear' },
  { term: 'Hydration', def: 'Managing fluid intake before, during and after training and racing.', category: 'Nutrition' },
  { term: 'Fuelling', def: 'Your plan for taking in carbohydrate and fluid to keep energy up through a long race.', category: 'Nutrition' },
  { term: 'Gut Training', def: 'Practising race-day fuelling in training so your stomach can handle the carbs and fluids on the day.', category: 'Nutrition' },
  { term: 'Carb Loading', def: 'Eating extra carbohydrate in the days before a long race to top up glycogen stores.', category: 'Nutrition' },
  { term: 'Real Food', def: 'Whole foods (bananas, rice cakes, chews) used alongside or instead of gels for fuelling.', category: 'Nutrition' },

  // ---- Gear / kit ----
  { term: 'Trisuit', def: 'A one- or two-piece suit worn for the whole race — swim, bike and run — with a light quick-drying pad.', category: 'Gear' },
  { term: 'Tri Shorts', def: 'Padded shorts with a thin chamois designed to be swum in, ridden in and run in.', category: 'Gear' },
  { term: 'Chamois', def: 'The padded insert in cycling/tri shorts. "Chamois cream" reduces chafing and saddle sores.', category: 'Gear' },
  { term: 'Cleats', def: 'The plates on the bottom of cycling shoes that clip into the pedals.', category: 'Gear' },
  { term: 'Clipless Pedals', def: 'Pedals your shoe cleat clips into (confusingly named — there’s no toe-clip cage).', category: 'Gear' },
  { term: 'Speed Laces / Elastic Laces', def: 'Stretchy or toggle laces that let you slip running shoes on instantly in T2.', category: 'Gear' },
  { term: 'Garmin / Wahoo', def: 'Popular brands of GPS watches and bike computers used to record and guide training and racing.', category: 'Gear' },
  { term: 'GPS Watch', def: 'A wrist device that tracks pace, distance, heart rate and more across all three disciplines.', category: 'Gear' },
  { term: 'Bike Computer', def: 'A handlebar-mounted unit showing speed, power, heart rate and navigation while riding.', category: 'Gear' },
  { term: 'DI / Dropper', def: 'Small aero add-ons like hydration or storage systems that tidy the bike; also "DI" for Di2 electronic shifting.', category: 'Gear' },
  { term: 'Anti-fog', def: 'Treatment or spit used to keep swim goggles clear.', category: 'Gear' },
  { term: 'Goggles', def: 'Eye protection for swimming; tinted for bright open water, clear for low light.', category: 'Gear' },
  { term: 'Swim Cap', def: 'A latex or silicone cap, often colour-coded to your wave and required by most races for visibility.', category: 'Gear' },

  // ================= EXPANSION PACK =================

  // ---- Strength / exercise ----
  { term: 'Rep', full: 'Repetition', def: 'One complete movement of an exercise, such as one squat or one press.', category: 'Strength' },
  { term: 'Set (strength)', def: 'A group of consecutive reps done without rest.', category: 'Strength' },
  { term: '1RM', full: 'One-Rep Max', def: 'The heaviest weight you can lift for a single rep — a benchmark of maximal strength.', category: 'Strength' },
  { term: 'Progressive Overload', def: 'Gradually increasing weight, reps or volume over time so the body keeps adapting and getting stronger.', category: 'Strength' },
  { term: 'Hypertrophy', def: 'Growth in muscle size, the goal of most bodybuilding-style training.', category: 'Strength' },
  { term: 'Compound Lift', def: 'A multi-joint exercise that works many muscles at once (squat, deadlift, bench press, row).', category: 'Strength' },
  { term: 'Isolation Exercise', def: 'A single-joint move targeting one muscle, like a biceps curl.', category: 'Strength' },
  { term: 'Squat', def: 'A fundamental lower-body lift: bend the hips and knees to lower, then stand back up.', category: 'Strength' },
  { term: 'Deadlift', def: 'Lifting a loaded barbell from the floor to standing — a full-body strength builder.', category: 'Strength' },
  { term: 'Bench Press', def: 'Pressing a barbell up from the chest while lying on a bench.', category: 'Strength' },
  { term: 'Overhead Press', def: 'Pressing weight from the shoulders up overhead.', category: 'Strength' },
  { term: 'Row', def: 'Pulling weight toward the torso to strengthen the upper back.', category: 'Strength' },
  { term: 'Pull-up', def: 'Pulling your body up to a bar using the back and arms.', category: 'Strength' },
  { term: 'Lunge', def: 'A single-leg strength and stability exercise, stepping forward or back into a knee bend.', category: 'Strength' },
  { term: 'Core', def: 'The trunk muscles (abdominals, lower back, hips) that stabilise the body and transfer power.', category: 'Strength' },
  { term: 'Plank', def: 'An isometric hold in a push-up-like position to build core stability.', category: 'Strength' },
  { term: 'Posterior Chain', def: 'The muscles along the back of the body (glutes, hamstrings, back) that drive running and cycling power.', category: 'Strength' },
  { term: 'Glutes', def: 'The buttock muscles — major power producers for pushing off in run and bike.', category: 'Strength' },
  { term: 'Eccentric', def: 'The lengthening (lowering) phase of a lift; builds strength and is a common cause of muscle soreness.', category: 'Strength' },
  { term: 'Concentric', def: 'The shortening (lifting) phase of a movement.', category: 'Strength' },
  { term: 'Isometric', def: 'A static contraction where the muscle works without changing length, like a plank or wall sit.', category: 'Strength' },
  { term: 'Time Under Tension', full: 'TUT', def: 'How long a muscle is under load during a set — a variable for building size.', category: 'Strength' },
  { term: 'Superset', def: 'Two exercises performed back-to-back with no rest in between.', category: 'Strength' },
  { term: 'Drop Set', def: 'Reducing the weight after reaching failure so you can keep repping.', category: 'Strength' },
  { term: 'Failure', def: 'The point in a set where you can no longer complete a rep with good form.', category: 'Strength' },
  { term: 'RIR', full: 'Reps In Reserve', def: 'How many more reps you could have done — a way to gauge how hard a set was.', category: 'Strength' },
  { term: 'Spotter', def: 'A partner who assists and keeps you safe during a heavy lift.', category: 'Strength' },
  { term: 'Barbell', def: 'A long bar loaded with weight plates on each end.', category: 'Strength' },
  { term: 'Dumbbell', def: 'A short, handheld free weight used singly or in pairs.', category: 'Strength' },
  { term: 'Kettlebell', def: 'A cast weight with a handle, used for swings and ballistic strength moves.', category: 'Strength' },
  { term: 'Squat Rack', def: 'A frame that holds a barbell for squatting and pressing safely.', category: 'Strength' },
  { term: 'Working Set', def: 'A challenging set performed at your target training weight (as opposed to a warm-up set).', category: 'Strength' },
  { term: 'Mobility', def: 'Usable range of motion around a joint — key for good technique and injury prevention.', category: 'Strength' },
  { term: 'Flexibility', def: 'How far a muscle can lengthen; supports mobility and comfortable positions.', category: 'Strength' },
  { term: 'Prehab', def: 'Preventive strength and mobility work done to avoid injuries before they happen.', category: 'Strength' },
  { term: 'Rehab', def: 'Targeted exercises to recover from and strengthen an injured area.', category: 'Strength' },
  { term: 'Activation', def: 'Waking up a muscle (e.g. glute activation drills) so it fires properly during a session.', category: 'Strength' },
  { term: 'Functional Training', def: 'Exercises that mimic real-world or sport-specific movement patterns.', category: 'Strength' },
  { term: 'Plyometrics', def: 'Explosive jump-based drills that build power and elastic strength.', category: 'Strength' },
  { term: 'Bodyweight Training', def: 'Strength work using your own body as the resistance — push-ups, squats, pull-ups.', category: 'Strength' },
  { term: 'DOMS Repeat Bout', def: 'The protective effect where a workout causes less soreness the second time you repeat it.', category: 'Strength' },

  // ---- Workout / session types ----
  { term: 'HIIT', full: 'High-Intensity Interval Training', def: 'Short bursts of near-maximal effort separated by brief recovery.', category: 'Workout' },
  { term: 'LISS', full: 'Low-Intensity Steady State', def: 'Easy, continuous cardio held at a low, steady effort for a long time.', category: 'Workout' },
  { term: 'AMRAP', full: 'As Many Rounds/Reps As Possible', def: 'Doing as much work as you can within a set time — a common conditioning format.', category: 'Workout' },
  { term: 'EMOM', full: 'Every Minute On the Minute', def: 'Start a set amount of work at the top of each minute; rest with whatever time is left.', category: 'Workout' },
  { term: 'Tabata', def: 'A HIIT protocol of 20 seconds hard and 10 seconds easy, repeated 8 times (4 minutes).', category: 'Workout' },
  { term: 'Circuit Training', def: 'Rotating through a series of exercise stations with little rest between them.', category: 'Workout' },
  { term: 'Pyramid', def: 'A workout where intensity or reps rise then fall (or fall then rise).', category: 'Workout' },
  { term: 'Ladder', def: 'Intervals or reps that step up or down in length across the set (e.g. 200-400-600-400-200).', category: 'Workout' },
  { term: 'Over-Unders', def: 'Intervals that alternate just above and just below threshold to sharpen that fitness.', category: 'Workout' },
  { term: 'VO2 Intervals', def: 'Hard efforts of roughly 3–5 minutes near max aerobic effort to raise VO2max.', category: 'Workout' },
  { term: 'Hill Repeats', def: 'Repeated hard efforts up a hill with easy jog/spin recoveries down.', category: 'Workout' },
  { term: 'Progression Run', def: 'A run that gradually gets faster, finishing at the strongest pace.', category: 'Workout' },
  { term: 'Long Run', def: 'The week’s longest run, building aerobic endurance and mental toughness.', category: 'Workout' },
  { term: 'Recovery Run', def: 'A short, very easy run that promotes blood flow and recovery without adding stress.', category: 'Workout' },
  { term: 'Easy Run', def: 'A relaxed, conversational-pace run — the backbone of most training weeks.', category: 'Workout' },
  { term: 'Shakeout', def: 'A short, gentle run or spin the day before a race to stay loose and calm nerves.', category: 'Workout' },
  { term: 'Warm-up', def: 'Easy activity and drills done before a session to prepare the body for harder work.', category: 'Workout' },
  { term: 'Cool-down', def: 'Easy activity after a session to gradually bring the body back to rest.', category: 'Workout' },
  { term: 'Dynamic Stretching', def: 'Active, moving stretches done as part of a warm-up.', category: 'Workout' },
  { term: 'Static Stretching', def: 'Holding a stretch in place, usually done after exercise.', category: 'Workout' },
  { term: 'Foam Rolling', def: 'Self-massage with a foam roller to ease tight muscles and aid recovery.', category: 'Workout' },
  { term: 'Cross-Training', def: 'Training in a different discipline to build fitness while reducing sport-specific strain.', category: 'Workout' },
  { term: 'Rest Day', def: 'A planned day off from training to let the body adapt and recover.', category: 'Workout' },
  { term: 'Work:Rest Ratio', def: 'The proportion of hard-effort time to recovery time in an interval session (e.g. 1:1).', category: 'Workout' },
  { term: 'Training Block', def: 'A multi-week phase of training focused on a specific goal or quality.', category: 'Workout' },
  { term: 'Threshold Session', def: 'A workout spent at or near threshold effort to raise your sustainable pace.', category: 'Workout' },
  { term: 'Sweet Spot', def: 'Training just below threshold (about 88–94% of FTP) — a time-efficient way to build fitness.', category: 'Workout' },
  { term: 'Track Workout', def: 'A structured speed session run on a 400 m track for precise pacing.', category: 'Workout' },
  { term: 'Repeats', def: 'Repeated hard efforts of a set distance or time with recovery between (e.g. 6 × 400 m).', category: 'Workout' },

  // ---- Ultra-running ----
  { term: 'Ultramarathon', def: 'Any running race longer than the marathon (42.2 km) — commonly 50K, 50 miles, 100K or 100 miles.', category: 'Ultra' },
  { term: '50K', def: 'A 50-kilometre ultra (about 31 miles), the most accessible ultra distance.', category: 'Ultra' },
  { term: '50-Miler', def: 'An 80 km ultra — a big step up from the marathon.', category: 'Ultra' },
  { term: '100K', def: 'A 100-kilometre ultra (about 62 miles).', category: 'Ultra' },
  { term: '100-Miler', def: 'A 100-mile ultra (161 km) — a landmark distance in the sport.', category: 'Ultra' },
  { term: 'Vert', def: 'Vertical gain: the total height climbed over a course, a key measure of a trail race’s difficulty.', category: 'Ultra' },
  { term: 'FKT', full: 'Fastest Known Time', def: 'The record for a set route, self-timed and verified by the trail-running community.', category: 'Ultra' },
  { term: 'UTMB', full: 'Ultra-Trail du Mont-Blanc', def: 'A ~170 km race around Mont Blanc — one of the most prestigious trail ultras in the world.', category: 'Ultra' },
  { term: 'Western States', def: 'The Western States 100 — the oldest 100-mile trail race, run in California.', category: 'Ultra' },
  { term: 'Badwater', def: 'Badwater 135, a 135-mile road ultra through Death Valley in extreme heat.', category: 'Ultra' },
  { term: 'Backyard Ultra', def: 'A last-one-standing race: run a 4.167-mile loop every hour until only one runner remains.', category: 'Ultra' },
  { term: 'Drop Bag', def: 'A bag of your own supplies left at an aid station to collect mid-race.', category: 'Ultra' },
  { term: 'Crew', def: 'Friends or family who meet you at aid stations with food, kit and encouragement.', category: 'Ultra' },
  { term: 'Pacer', def: 'A companion runner allowed to accompany you through the later stages of an ultra.', category: 'Ultra' },
  { term: 'Buckle', def: 'The belt buckle awarded for finishing a 100-miler, often tiered by finish time (e.g. sub-24-hour).', category: 'Ultra' },
  { term: 'Sub-24', def: 'Finishing a 100-mile race in under 24 hours — a major achievement.', category: 'Ultra' },
  { term: 'Hotspot', def: 'An early warning sign of a blister — a hot, rubbing patch on the foot.', category: 'Ultra' },
  { term: 'Chafing', def: 'Skin irritation from repeated rubbing of skin or clothing, managed with lubricant.', category: 'Ultra' },
  { term: 'Anti-Chafe', def: 'Balm or lubricant applied to skin to prevent chafing over long distances.', category: 'Ultra' },
  { term: 'Gaiters', def: 'Light fabric covers over the shoe and ankle to keep out trail grit and stones.', category: 'Ultra' },
  { term: 'Trekking Poles', def: 'Poles used on steep climbs to save the legs and improve balance.', category: 'Ultra' },
  { term: 'Power Hiking', def: 'Fast, purposeful uphill hiking that is often more efficient than running steep grades.', category: 'Ultra' },
  { term: 'Runnable', def: 'Terrain gradual and smooth enough to run rather than hike.', category: 'Ultra' },
  { term: 'Technical Trail', def: 'Rough ground with rocks, roots and uneven footing that demands careful foot placement.', category: 'Ultra' },
  { term: 'Single Track', def: 'A narrow trail wide enough for only one runner at a time.', category: 'Ultra' },
  { term: 'Switchbacks', def: 'Zig-zag turns that ease the gradient of a steep climb or descent.', category: 'Ultra' },
  { term: 'Night Section', def: 'The overnight portion of a long ultra, run by headtorch.', category: 'Ultra' },
  { term: 'Headtorch', def: 'A head-worn lamp for running in the dark.', category: 'Ultra' },
  { term: 'Sleep Deprivation', def: 'Pushing through long races without sleep, a defining challenge of multi-day and 100-mile events.', category: 'Ultra' },
  { term: 'Dark Place', def: 'The low point most ultrarunners hit, where the challenge becomes mental as much as physical.', category: 'Ultra' },
  { term: 'Vertical K', full: 'VK', def: 'A short, brutally steep race that climbs 1,000 m of vertical.', category: 'Ultra' },
  { term: 'Skyrunning', def: 'Racing in high mountains over steep, technical terrain, often above 2,000 m.', category: 'Ultra' },
  { term: 'Stage Race', def: 'A multi-day race with a timed stage each day, results totalled across days.', category: 'Ultra' },
  { term: 'Self-Supported', def: 'A race format where you carry all your own food and gear between checkpoints.', category: 'Ultra' },
  { term: 'Marathon des Sables', def: 'A famous multi-stage, self-supported ultra across the Sahara Desert.', category: 'Ultra' },
  { term: 'Comrades', def: 'The Comrades Marathon, an iconic ~90 km ultra in South Africa.', category: 'Ultra' },
  { term: 'Elevation Profile', def: 'A chart of a course’s climbs and descents used to plan pacing and effort.', category: 'Ultra' },
  { term: 'Time Barrier', def: 'A cut-off time you must beat at a checkpoint to continue in the race.', category: 'Ultra' },
  { term: 'Low Mileage Week', def: 'A deliberately reduced-volume week to absorb training and stay fresh.', category: 'Ultra' },
  { term: 'DNF Rate', def: 'The proportion of starters who fail to finish — often high in tough ultras.', category: 'Ultra' },

  // ---- Pure swimming ----
  { term: 'Freestyle', def: 'Front crawl — the fastest stroke and the one used for almost all triathlon swimming.', category: 'Swim' },
  { term: 'Backstroke', def: 'A stroke swum on the back, alternating arm pulls.', category: 'Swim' },
  { term: 'Breaststroke', def: 'A stroke with a simultaneous arm sweep and a frog kick.', category: 'Swim' },
  { term: 'Butterfly', def: 'A powerful stroke with a simultaneous double-arm pull and dolphin kick.', category: 'Swim' },
  { term: 'Individual Medley', full: 'IM (swimming)', def: 'A race using all four strokes in order: butterfly, backstroke, breaststroke, then freestyle.', category: 'Swim' },
  { term: 'Flip Turn', def: 'A somersault turn at the wall that lets you change direction without stopping. Also called a tumble turn.', category: 'Swim' },
  { term: 'Streamline', def: 'The tight, arms-extended, head-tucked position held off each wall to cut drag.', category: 'Swim' },
  { term: 'Catch-up Drill', def: 'A drill where one hand waits out front until the other catches up, teaching stroke timing.', category: 'Swim' },
  { term: 'Kickboard', def: 'A foam board held out front to isolate and train the leg kick.', category: 'Swim' },
  { term: 'Fins', def: 'Swim fins worn on the feet to build kick strength and ankle flexibility.', category: 'Swim' },
  { term: 'Snorkel', def: 'A centre-mounted snorkel that lets you focus on stroke technique without turning to breathe.', category: 'Swim' },
  { term: 'Pace Clock', def: 'The large poolside clock used to time swim repeats and rest intervals.', category: 'Swim' },
  { term: 'Send-off', def: 'The interval time on which you start each repeat in a set (e.g. "100s on 1:40").', category: 'Swim' },
  { term: 'Main Set', def: 'The core, hardest part of a swim session, sandwiched between warm-up and cool-down.', category: 'Swim' },
  { term: 'DPS', full: 'Distance Per Stroke', def: 'How far you travel with each arm stroke — a measure of swimming efficiency.', category: 'Swim' },
  { term: 'Stroke Count', def: 'The number of strokes taken per pool length; fewer usually means a more efficient stroke.', category: 'Swim' },
  { term: 'Hypoxic Set', def: 'Swimming with reduced breathing frequency (e.g. every 5 or 7 strokes) to build breath control.', category: 'Swim' },
  { term: 'Circle Swimming', def: 'Swimming in a loop (usually anticlockwise) so several swimmers can share one lane.', category: 'Swim' },
  { term: 'Lane Etiquette', def: 'The unwritten rules of sharing a lane: circle swim, seed by speed, and let faster swimmers pass.', category: 'Swim' },
  { term: 'Sculling', def: 'Small figure-eight hand movements used to feel and hold the water; a technique drill.', category: 'Swim' },
  { term: 'High Elbow', def: 'Keeping the elbow higher than the hand early in the pull for a stronger catch.', category: 'Swim' },
  { term: 'Rotation', def: 'Rolling the body along its long axis with each stroke to lengthen the reach and use the core.', category: 'Swim' },
  { term: 'Descending Set', def: 'A set of repeats swum progressively faster, each quicker than the last.', category: 'Swim' },
  { term: 'Kick Set', def: 'A set swum using the legs only, often with a kickboard.', category: 'Swim' },
  { term: 'Pull Set', def: 'A set swum with a pull buoy (and often paddles), using the arms only.', category: 'Swim' },
  { term: 'Open Turn', def: 'A simple touch-and-go turn at the wall, used in breaststroke and butterfly.', category: 'Swim' },
  { term: 'Two-Beat Kick', def: 'A kicking pattern with two kicks per full stroke cycle, common in distance freestyle.', category: 'Swim' },
  { term: 'Six-Beat Kick', def: 'A kicking pattern with six kicks per stroke cycle, used for speed and sprinting.', category: 'Swim' },
  { term: 'Glide', def: 'The brief forward stretch between strokes where the body travels through the water.', category: 'Swim' },
  { term: 'Drill', def: 'A focused exercise that breaks the stroke into parts to improve technique.', category: 'Swim' },

  // ---- Pure running ----
  { term: 'Foot Strike', def: 'Where the foot first lands — heel, midfoot or forefoot.', category: 'Run' },
  { term: 'Heel Strike', def: 'Landing on the heel first; the most common running foot strike.', category: 'Run' },
  { term: 'Midfoot Strike', def: 'Landing flat on the midfoot, often encouraged for efficiency.', category: 'Run' },
  { term: 'Forefoot Strike', def: 'Landing on the ball of the foot first, common at faster paces.', category: 'Run' },
  { term: 'Gait', def: 'Your individual pattern of movement while running.', category: 'Run' },
  { term: 'Gait Analysis', def: 'An assessment of your running form, usually filmed on a treadmill, to guide shoes or technique.', category: 'Run' },
  { term: 'Pronation', def: 'The natural inward roll of the foot as it lands and absorbs shock.', category: 'Run' },
  { term: 'Overpronation', def: 'Excessive inward foot roll, sometimes addressed with supportive shoes.', category: 'Run' },
  { term: 'Supination', def: 'Outward roll of the foot on landing (underpronation).', category: 'Run' },
  { term: 'Ground Contact Time', def: 'How long the foot stays on the ground each step; shorter is generally more economical.', category: 'Run' },
  { term: 'Vertical Oscillation', def: 'How much you bounce up and down as you run; less bounce usually means more efficiency.', category: 'Run' },
  { term: 'Stride Length', def: 'The distance covered with each running step.', category: 'Run' },
  { term: 'Turnover', def: 'Your step rate (cadence); many runners aim for a quick, light 170–180 steps per minute.', category: 'Run' },
  { term: 'Pace', def: 'Your speed expressed as time per mile or kilometre.', category: 'Run' },
  { term: 'Threshold Run', def: 'A sustained run at threshold effort — comfortably hard, near your one-hour race pace.', category: 'Run' },
  { term: 'Runner’s High', def: 'The euphoric, calm feeling that can arrive during or after prolonged running.', category: 'Run' },
  { term: 'Runner’s Knee', def: 'Pain around the kneecap (patellofemoral pain), a common overuse complaint.', category: 'Run' },
  { term: 'Shin Splints', def: 'Pain along the shin bone from overuse, common when ramping up mileage too fast.', category: 'Run' },
  { term: 'IT Band Syndrome', def: 'Pain on the outside of the knee from a tight iliotibial band.', category: 'Run' },
  { term: 'Plantar Fasciitis', def: 'Heel and arch pain from irritation of the tissue along the sole of the foot.', category: 'Run' },
  { term: 'Achilles Tendinopathy', def: 'Pain and stiffness in the Achilles tendon from overload.', category: 'Run' },
  { term: 'Marathon', def: 'A 42.2 km (26.2 mile) road race — the classic long-distance running event.', category: 'Run' },
  { term: 'Half Marathon', def: 'A 21.1 km (13.1 mile) road race.', category: 'Run' },
  { term: '10K', def: 'A 10-kilometre race, a popular road-racing distance.', category: 'Run' },
  { term: '5K', def: 'A 5-kilometre race, the classic entry-point running distance.', category: 'Run' },
  { term: 'Parkrun', def: 'A free, timed, weekly 5 km community run held in parks worldwide.', category: 'Run' },
  { term: 'Heel-to-Toe Drop', def: 'The height difference between a shoe’s heel and forefoot, measured in millimetres.', category: 'Run' },
  { term: 'Stack Height', def: 'The amount of foam/cushioning between the foot and the ground in a shoe.', category: 'Run' },
  { term: 'Carbon Plate', def: 'A stiff plate embedded in racing shoes that improves running economy.', category: 'Run' },
  { term: 'Super Shoes', def: 'Highly cushioned, carbon-plated racing shoes that boost performance.', category: 'Run' },
  { term: 'Zero Drop', def: 'A shoe with the heel and forefoot at the same height.', category: 'Run' },
  { term: 'Fasted Run', def: 'An easy run done before eating, sometimes used to train fat metabolism.', category: 'Run' },

  // ---- Pure bike ----
  { term: 'Peloton', def: 'The main bunch of riders in a road race, sheltering in each other’s draft.', category: 'Bike' },
  { term: 'Echelon', def: 'A diagonal line of riders staggered across the road to share shelter from a crosswind.', category: 'Bike' },
  { term: 'Paceline', def: 'A line of riders taking turns at the front so the group goes faster for less effort.', category: 'Bike' },
  { term: 'Pull (cycling)', def: 'Taking your turn at the front of a group, into the wind, before swinging off.', category: 'Bike' },
  { term: 'Getting Dropped', def: 'Being unable to hold the group’s pace and falling off the back.', category: 'Bike' },
  { term: 'Attack', def: 'A sudden, sharp acceleration to break away from other riders.', category: 'Bike' },
  { term: 'Breakaway', def: 'A rider or small group that has escaped off the front of the peloton.', category: 'Bike' },
  { term: 'Bridge', def: 'Closing the gap from one group across to another ahead.', category: 'Bike' },
  { term: 'Domestique', def: 'A rider who sacrifices their own result to support a team leader.', category: 'Bike' },
  { term: 'Cassette', def: 'The cluster of sprockets on the rear wheel that make up the gears.', category: 'Bike' },
  { term: 'Chainring', def: 'The toothed front gear(s) attached to the cranks.', category: 'Bike' },
  { term: 'Crankset', def: 'The arms that the pedals attach to, turning your pedalling into drive.', category: 'Bike' },
  { term: 'Derailleur', def: 'The mechanism that shifts the chain across the gears, front or rear.', category: 'Bike' },
  { term: 'Bottom Bracket', def: 'The bearing assembly the cranks spin on, housed in the frame.', category: 'Bike' },
  { term: 'Headset', def: 'The bearings that let the fork and handlebars steer smoothly.', category: 'Bike' },
  { term: 'Gear Ratio', def: 'The relationship between front and rear gear sizes that sets how hard or easy each gear is.', category: 'Bike' },
  { term: 'Spinning', def: 'Pedalling at a high cadence in an easier gear.', category: 'Bike' },
  { term: 'Mashing', def: 'Grinding a big, hard gear at low cadence — powerful but fatiguing.', category: 'Bike' },
  { term: 'Granny Gear', def: 'The easiest, lowest gear, used for the steepest climbs.', category: 'Bike' },
  { term: 'Cross-Chaining', def: 'Running the chain at an extreme angle (big-big or small-small), which is inefficient and wears parts.', category: 'Bike' },
  { term: 'Hoods', def: 'The rubber covers on top of the brake levers where riders often rest their hands.', category: 'Bike' },
  { term: 'Drops', def: 'The lower, curved section of road handlebars, used for a more aero position.', category: 'Bike' },
  { term: 'Tyre Pressure', def: 'How firmly the tyres are inflated (in PSI or bar), tuned for grip and rolling speed.', category: 'Bike' },
  { term: 'Rolling Resistance', def: 'The energy lost as a tyre deforms on the road — lower means free speed.', category: 'Bike' },
  { term: 'Puncture', def: 'A flat tyre caused by a hole letting the air out.', category: 'Bike' },
  { term: 'Pinch Flat', def: 'A puncture caused by the tube being squeezed against the rim, often from hitting a bump.', category: 'Bike' },
  { term: 'Dropper Post', def: 'A seatpost that can be lowered on the fly at the push of a button, common off-road.', category: 'Bike' },
  { term: 'Cadence Sensor', def: 'A small device that measures how fast you are pedalling (RPM).', category: 'Bike' },
  { term: 'Sportive', def: 'A long, organised mass-participation road ride, timed but not usually a race.', category: 'Bike' },
  { term: 'Gran Fondo', def: 'A large organised long-distance road ride, often with timed sections.', category: 'Bike' },
  { term: 'Criterium', full: 'Crit', def: 'A short, fast, multi-lap bike race on a closed city-centre circuit.', category: 'Bike' },
  { term: 'Soft-Pedal', def: 'Turning the pedals lightly without putting in real effort.', category: 'Bike' },
  { term: 'Coasting', def: 'Rolling along without pedalling.', category: 'Bike' },
  { term: 'KOM / QOM', full: 'King / Queen of the Mountain', def: 'The fastest recorded time on a climb or a Strava segment.', category: 'Bike' },
  { term: 'Segment', def: 'A defined stretch of road or trail that riders’ times are ranked on, popularised by Strava.', category: 'Bike' },
  { term: 'Gravel', def: 'Riding or racing on unpaved roads and tracks, usually on a drop-bar gravel bike.', category: 'Bike' },
  { term: 'MTB', full: 'Mountain Bike', def: 'Off-road cycling on rugged trails, with fat knobbly tyres and suspension.', category: 'Bike' },
  { term: 'N+1', def: 'The tongue-in-cheek rule that the correct number of bikes to own is always one more than you have.', category: 'Bike' },

  // ---- Longevity / health ----
  { term: 'Healthspan', def: 'The years of life spent in good health, free of chronic disease — the real goal of longevity training.', category: 'Longevity' },
  { term: 'Lifespan', def: 'The total number of years lived; longevity work aims to stretch healthspan within it, not just add years.', category: 'Longevity' },
  { term: 'Longevity', def: 'Living a long and, above all, healthy and capable life — the umbrella theme.', category: 'Longevity' },
  { term: 'All-Cause Mortality', def: 'The risk of dying from any cause; fitness markers like VO2max and grip strength strongly predict it.', category: 'Longevity' },
  { term: 'Cardiorespiratory Fitness', full: 'CRF', def: 'Overall aerobic fitness (closely tied to VO2max) — one of the strongest predictors of a long, healthy life.', category: 'Longevity' },
  { term: 'Sarcopenia', def: 'The age-related loss of muscle mass and strength; resistance training is the main defence.', category: 'Longevity' },
  { term: 'Osteoporosis', def: 'Loss of bone density that raises fracture risk; weight-bearing and resistance exercise help protect bone.', category: 'Longevity' },
  { term: 'Muscle Mass', def: 'The amount of muscle on the body — protective for metabolism, strength, balance and longevity.', category: 'Longevity' },
  { term: 'Grip Strength', def: 'How strongly you can grip; a simple, surprisingly strong predictor of overall strength and longevity.', category: 'Longevity' },
  { term: 'Stability', def: 'The ability to control your joints and body through movement — key to avoiding injury and falls with age.', category: 'Longevity' },
  { term: 'Fall Risk', def: 'The likelihood of falling, which rises with age and is reduced by balance and strength work.', category: 'Longevity' },
  { term: 'Autophagy', def: 'The body’s process of clearing out and recycling damaged cell parts, boosted by exercise and fasting.', category: 'Longevity' },
  { term: 'Mitochondria', def: 'The tiny power plants inside cells that produce energy; endurance training builds more of them.', category: 'Longevity' },
  { term: 'Mitochondrial Biogenesis', def: 'The creation of new mitochondria, driven by aerobic training — more engines for endurance.', category: 'Longevity' },
  { term: 'Metabolic Health', def: 'How well the body manages blood sugar, fats and energy — central to avoiding chronic disease.', category: 'Longevity' },
  { term: 'Insulin Sensitivity', def: 'How responsive your cells are to insulin; exercise improves it and protects against type 2 diabetes.', category: 'Longevity' },
  { term: 'Blood Glucose', def: 'The level of sugar in the blood; keeping it stable supports metabolic health and energy.', category: 'Longevity' },
  { term: 'Inflammation', def: 'The immune system’s response to stress or injury; chronic low-grade inflammation is linked to ageing.', category: 'Longevity' },
  { term: 'Resting Heart Rate', def: 'Your heart rate at complete rest; a lower value generally reflects better fitness.', category: 'Longevity' },
  { term: 'Heart Rate Variability', full: 'HRV', def: 'The variation in time between heartbeats; higher usually signals good recovery and a healthy nervous system.', category: 'Longevity' },
  { term: 'Blood Pressure', def: 'The force of blood against artery walls; regular exercise helps keep it in a healthy range.', category: 'Longevity' },
  { term: 'Cholesterol', def: 'Fatty substances in the blood; the balance of LDL and HDL relates to heart-disease risk.', category: 'Longevity' },
  { term: 'LDL / HDL', def: 'The "bad" (LDL) and "good" (HDL) cholesterol carriers used to gauge cardiovascular risk.', category: 'Longevity' },
  { term: 'MET', full: 'Metabolic Equivalent of Task', def: 'A unit of exercise intensity where 1 MET equals sitting at rest; brisk activity is several METs.', category: 'Longevity' },
  { term: 'NEAT', full: 'Non-Exercise Activity Thermogenesis', def: 'The energy burned through everyday movement — walking, chores, fidgeting — outside formal workouts.', category: 'Longevity' },
  { term: 'Rucking', def: 'Walking with a weighted pack; a low-impact way to combine strength and cardio, popular in longevity circles.', category: 'Longevity' },
  { term: 'Zone 2 Base', def: 'Easy aerobic training that builds the mitochondrial and metabolic base linked to long-term health.', category: 'Longevity' },
  { term: 'Fasting', def: 'Going without food for a set period; studied for its effects on metabolism and cellular clean-up.', category: 'Longevity' },
  { term: 'Time-Restricted Eating', def: 'Confining daily eating to a set window (for example eight hours) as a metabolic-health strategy.', category: 'Longevity' },
  { term: 'Cold Exposure', def: 'Deliberate cold, such as ice baths or cold showers, used for recovery and resilience.', category: 'Longevity' },
  { term: 'Heat Exposure', def: 'Sauna and heat sessions, linked in studies to cardiovascular and recovery benefits.', category: 'Longevity' },
  { term: 'Sleep Hygiene', def: 'The habits and environment that support consistent, high-quality sleep — a foundation of recovery.', category: 'Longevity' },
  { term: 'Deep Sleep', def: 'The restorative slow-wave stage of sleep important for physical recovery.', category: 'Longevity' },
  { term: 'REM Sleep', def: 'The dreaming stage of sleep, important for brain function and memory.', category: 'Longevity' },
  { term: 'Blue Zones', def: 'Regions of the world with unusually many people living to 100, studied for their lifestyle habits.', category: 'Longevity' },
  { term: 'Centenarian', def: 'Someone who reaches the age of 100 or more.', category: 'Longevity' },
  { term: 'VO2max Longevity Link', def: 'The well-established finding that higher VO2max is associated with markedly lower risk of early death.', category: 'Longevity' },
  { term: 'Exercise Snack', def: 'A very short bout of activity (like a minute of stair-climbing) sprinkled through the day for health.', category: 'Longevity' },
];
